version: '3'

services:
  mysql_db:
    image: mysql

    environment:
      - MYSQL_ROOT_PASSWORD=1111
      - MYSQL_DATABASE=car_rental_db
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=1111

  springboot-docker-container:
    image: car-rental
    ports:
    - 8080:8080
    build:
      context: ./
      dockerfile: Dockerfile

    depends_on:
      - mysql_db
